### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by amitsaha** [IDSIA/brainstorm#68]
As the title suggests, please add an appropriate open source license so that potential contributors are aware of that. It will also help when somebody decides to submit packages to official Linux distribution repos. 
.

**Comment by flukeskywalker** [comment]
There is a LICENSE file with the necessary info, but I presume you mean adding some license info to the README? If so, I agree that will be helpful, and we'll do it.

**Comment by amitsaha** [comment]
Cool, thanks.
