### ISSUE TITLE
Make CPU / Numpy handler default in examples rather than PyCUDA

### ISSUE THREAD

**Issue by pranv** [IDSIA/brainstorm#82]
Reason: A lot of people will be just trying out. The GPU setup is more complicated.

I think some of the success of things like char-rnn etc., were due to the fact that people could just download them and run.

**Comment by flukeskywalker** [comment]
Good point. Will change the CIFAR-10 and Hutter example to be similar to the MNIST one.

**Comment by flukeskywalker** [comment]
357b5416b35a8223881337cb0ebfe82d3dc46a70 addresses this, and also provides a README for the examples directory.

**Comment by pranv** [comment]
Neat!
