### ISSUE TITLE
Specify six version

### ISSUE THREAD

**Issue by Kaixhin** [IDSIA/brainstorm#88]
As pointed out in https://github.com/IDSIA/brainstorm/pull/87, the default version of `six` included with Ubuntu (14.04 in my case) is too old, which means a minimum version should be specified in the [requirements](https://github.com/IDSIA/brainstorm/blob/master/requirements.txt).

**Comment by flukeskywalker** [comment]
Thanks! I added this to the docs branch which will be merged in a couple of days.

**Comment by flukeskywalker** [comment]
Perhaps it would be better to switch to the ``future`` package. ``six`` can easily cause problems for people not using a virtualenv.

**Comment by Kaixhin** [comment]
Just going through my issues and spotted this. Are you still planning to merge the `docs` branch?
