### ISSUE TITLE
Explain how brainstorm compares to alternatives

### ISSUE THREAD

**Issue by iver56** [IDSIA/brainstorm#90]
I think that README lacks some information such as:
- How brainstorm compares to PyBrain, Theano, Caffe, TensorFlow, CNTK, Torch and others. What makes brainstorm better and/or different?
- Some cases where brainstorm is not apt, and an alternative should be used. For example, tell that it might not work on all kinds of GPUs and operating systems.

**Comment by iaroslav-ai** [comment]
+1 I have the same questions.

**Comment by iver56** [comment]
Brainstorm is currently one of the least used among all deep learning libraries. At this point it makes sense to use a more actively maintained library, such as TensorFlow

Reference:
https://news.ycombinator.com/item?id=11801469
