### ISSUE TITLE
MomentumStepper has error

### ISSUE THREAD

**Issue by julian121266** [IDSIA/brainstorm#96]
The momentum stepper should implement the following equations:
v=gamma*v + alpha * g  (g is gradient)
theta = theta - v
Instead the implementation does:
v=gamma*v - alpha * g
theta = theta + v.

In essence there is a sign error. Will submit a pull request soon.

**Comment by flukeskywalker** [comment]
Are you sure? See: 
http://machinelearning.wustl.edu/mlpapers/paper_files/icml2013_sutskever13.pdf 
or 
http://publications.idiap.ch/downloads/reports/1995/95-04.pdf

The way to understand it is that we'd normally have θ -> θ - αg. Instead, we want to do θ -> θ -αg + γv i.e. add a velocity vector. What we add at this step in total is the *effective* velocity (needed for next step), which is - αg + γv.

**Comment by julian121266** [comment]
Thank you Rupesh for the reply. 

Looking closer at it I suppose the two ways are equivalent. 

See you tomorrow.
